Synapsify combined studies
MEP-LINCS/MEP_LINCS pull request #82
Opened 2017-04-05 17:14 UTC by markdane

@kdaily Modified the combined studies dataset to read level 3 and 4 files from multiple studies from Synpase, normalize the common signals, add in the staining set specific signals then write out levels 3 and 4 with annotations and provenances.

This commit also include error checking on the signals in the QA_SpotMEP report and adds some uploader files to the archive folder.

2017-04-05 22:40 UTC, kdaily commented on Pipeline/PreprocessCombinedStudies.R
> +  parser <- OptionParser(usage = "%prog [options] barcode file", option_list=option_list)
BARCODE OUTPUTFILE

2017-04-05 22:54 UTC, kdaily requested changes

2017-04-05 22:54 UTC, kdaily commented on Pipeline/PreprocessCombinedStudies.R
> +cl <- getCSCommandLineArgs()
getCommandLineArgs

2017-04-05 22:54 UTC, kdaily commented on Pipeline/PreprocessCombinedStudies.R
> +                help="Path to local input data directory or Synapse ID for a File View."),
can't give local file path - change param name to make it more clear that it works differently from others

2017-04-05 22:54 UTC, kdaily commented on Pipeline/PreprocessCombinedStudies.R
> +if(nrow(unique(annotations[,.(Study,Segmentation,Preprocess,DataType,Consortia,Drug)]))>1) stop("Cannot comnbine studies with mixed annotations")
typo

2017-04-05 22:54 UTC, kdaily commented on Pipeline/PreprocessCombinedStudies.R
> +write.table(mepDT, paste0(path,"/study/",studyNameSSC,"/Annotated/",studyNameSSC,"_Level4.tsv"), sep = "\t",row.names = FALSE, quote=FALSE)
temp folder

2017-04-06 01:29 UTC, markdane commented on Pipeline/PreprocessCombinedStudies.R
> +                help="Path to local input data directory or Synapse ID for a File View."),
make_option(c("-i", "--inputSynID"), type="character", default=NULL, metavar="synID",
                help="Synapse ID for a File View with input data."),

2017-04-06 01:51 UTC, merged